<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.7</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<name>My Area Guide</name>

	<groupId>ru.practicum</groupId>
	<artifactId>my-area-guide</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<modules>
		<module>stats</module>
		<module>core</module>
		<module>infra</module>
	</modules>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>21</java.version>
		<!-- DEPENDENCIES -->
		<avro.version>1.12.1</avro.version>
		<grpc.version>1.76.0</grpc.version>
		<protobuf.version>4.33.1</protobuf.version>
		<grpc-spring-boot-starter.version>3.1.0.RELEASE</grpc-spring-boot-starter.version>
		<stats-client.version>0.0.1-SNAPSHOT</stats-client.version>
		<spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
		<!-- PLUGINS -->
		<protobuf-plugin.version>4.0.2</protobuf-plugin.version>
	</properties>

	<dependencyManagement>
		<dependencies>

			<!-- INTERNAL DEPENDENCIES -->

			<dependency>
				<groupId>ru.practicum</groupId>
				<artifactId>stats-client</artifactId>
				<version>${stats-client.version}</version>
			</dependency>

			<dependency>
				<groupId>ru.practicum</groupId>
				<artifactId>stats-common</artifactId>
				<version>${stats-client.version}</version>
			</dependency>

			<dependency>
				<groupId>ru.practicum</groupId>
				<artifactId>core-common</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>ru.practicum</groupId>
				<artifactId>proto-schemas</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>ru.practicum</groupId>
				<artifactId>avro-schemas</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- CLOUD DEPENDENCIES -->

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud-dependencies.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- KAFKA DEPENDENCIES -->

			<dependency>
				<groupId>org.apache.avro</groupId>
				<artifactId>avro</artifactId>
				<version>${avro.version}</version>
			</dependency>

			<!-- GRPC DEPENDENCIES -->

			<dependency>
				<groupId>net.devh</groupId>
				<artifactId>grpc-spring-boot-starter</artifactId>
				<version>${grpc-spring-boot-starter.version}</version>
			</dependency>

			<dependency>
				<groupId>net.devh</groupId>
				<artifactId>grpc-server-spring-boot-starter</artifactId>
				<version>${grpc-spring-boot-starter.version}</version>
			</dependency>

			<dependency>
				<groupId>net.devh</groupId>
				<artifactId>grpc-client-spring-boot-starter</artifactId>
				<version>${grpc-spring-boot-starter.version}</version>
			</dependency>

			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-core</artifactId>
				<version>${grpc.version}</version>
			</dependency>

			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-stub</artifactId>
				<version>${grpc.version}</version>
			</dependency>

			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-api</artifactId>
				<version>${grpc.version}</version>
			</dependency>

			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-protobuf</artifactId>
				<version>${grpc.version}</version>
			</dependency>

			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-netty-shaded</artifactId>
				<version>${grpc.version}</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
				</plugin>

				<plugin>
					<groupId>org.apache.avro</groupId>
					<artifactId>avro-maven-plugin</artifactId>
					<version>${avro.version}</version>
				</plugin>

				<plugin>
					<groupId>io.github.ascopes</groupId>
					<artifactId>protobuf-maven-plugin</artifactId>
					<version>${protobuf-plugin.version}</version>
				</plugin>

			</plugins>
		</pluginManagement>
	</build>

</project>
